services:
  - type: web
    name: varsity-plug-app  # Your app's name on Render
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn varsity_plug.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true  # Render auto-generates a secure key
      - key: DATABASE_URL
        fromDatabase:
          name: varsity-plug-db  # Only if using PostgreSQL
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false  # Manually set this in Render's dashboard
    staticFiles:
      - path: /static
        destination: staticfiles