services:
  - type: web
    name: varsity-plug
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      cd $(pwd)
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      # Wait for database to be ready
      while ! nc -z $DATABASE_HOST $DATABASE_PORT; do
        echo "Waiting for database connection..."
        sleep 2
      done
      python manage.py migrate
      gunicorn varsity_plug.wsgi:application --bind 0.0.0.0:$PORT --chdir $(pwd)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: varsity_plug.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: varsity-plug-db
          property: connectionString
      - key: DATABASE_HOST
        fromDatabase:
          name: varsity-plug-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: varsity-plug-db
          property: port
      - key: REDIS_URL
        fromService:
          type: redis
          name: varsity-plug-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: varsity-plug.onrender.com

databases:
  - name: varsity-plug-db
    databaseName: varsity_plug
    user: varsity_plug
    plan: free

services:
  - type: redis
    name: varsity-plug-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []