services:
  - type: web
    name: varsityplugapp
    runtime: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --verbosity 2
    startCommand: python manage.py migrate && python manage.py createsuperuser_auto --noinput || true && gunicorn varsity_plug.wsgi:application
    postBuild: apt-get update && apt-get install -y tesseract-ocr libtesseract-dev poppler-utils
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: varsity_plug_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: varsity_plug_redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
  - type: redis
    name: varsity_plug_redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: varsity_plug_db
    databaseName: varsity_plug_db
    user: varsity_plug_db_user
    region: oregon