services:
  - type: web
    name: varsity-plug
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Checking database connection..."
      python -c "
      import os
      import psycopg2
      from urllib.parse import urlparse
      url = urlparse(os.getenv('DATABASE_URL'))
      conn = psycopg2.connect(
          dbname=url.path[1:],
          user=url.username,
          password=url.password,
          host=url.hostname,
          port=url.port
      )
      print('Database connection successful!')
      conn.close()
      "
      echo "Running migrations..."
      python manage.py showmigrations --list
      echo "Applying migrations..."
      python manage.py migrate auth --noinput --verbosity 2
      python manage.py migrate contenttypes --noinput --verbosity 2
      python manage.py migrate sessions --noinput --verbosity 2
      python manage.py migrate admin --noinput --verbosity 2
      python manage.py migrate helper --noinput --verbosity 2
      echo "Collecting static files..."
      python manage.py collectstatic --noinput
    startCommand: |
      cd $(pwd)
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      # Wait for database to be ready
      while ! nc -z $DATABASE_HOST $DATABASE_PORT; do
        echo "Waiting for database connection..."
        sleep 2
      done
      echo "Starting gunicorn..."
      gunicorn varsity_plug.wsgi:application --bind 0.0.0.0:$PORT --chdir $(pwd)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: varsity_plug.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: postgresql://varsityplug_db_user:UDXToSK9S3Sn2jL6loHYNhMNeIa24Fb2@dpg-d0hnbst6ubrc73ah17g0-a/varsityplug_db
      - key: DATABASE_HOST
        value: dpg-d0hnbst6ubrc73ah17g0-a
      - key: DATABASE_PORT
        value: 5432
      - key: REDIS_URL
        fromService:
          type: redis
          name: varsity-plug-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: varsityplug-nvg2.onrender.com

databases:
  - name: varsity-plug-db
    databaseName: varsity_plug
    user: varsity_plug
    plan: free

services:
  - type: redis
    name: varsity-plug-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []