services:
  - type: web
    name: varsity-plug-app
    runtime: python
    buildCommand: >-
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    preDeploy: >-
      python manage.py migrate &&
      python manage.py createsuperuser_auto
    startCommand: gunicorn varsity_plug.wsgi:application
    postBuild: >-
      apt-get update &&
      apt-get install -y tesseract-ocr
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://varsity_plug_db_user:1dOGthjtnXPsff38kIdMtw4vM2NF1OUa@dpg-d033gnadbo4c73c8f1i0-a.oregon-postgres.render.com/varsity_plug_db"
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPERUSER_PASSWORD
        sync: false  # Set manually in Render dashboard
databases:
  - name: varsity-plug-db
    databaseName: varsity_plug_db
    user: varsity_plug_db_user