services:
  - type: web
    name: varsity-plug
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn varsity_plug.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: varsity_plug.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: varsity-plug-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: varsity-plug-redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: varsity-plug-db
    databaseName: varsity_plug
    user: varsity_plug
    plan: free

services:
  - type: redis
    name: varsity-plug-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []