services:
  - type: web
    name: varsityplugapp
    runtime: python
    region: oregon
    plan: free
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --verbosity 2
    startCommand: python manage.py migrate --noinput && gunicorn varsity_plug.wsgi:application --workers 2 --timeout 120
    healthCheckPath: /health/
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: varsity_plug_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: varsity_plug_redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_LOG_LEVEL
        value: "INFO"
  - type: redis
    name: varsity_plug_redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: varsity_plug_db
    databaseName: varsity_plug_db
    user: varsity_plug_db_user
    region: oregon
    plan: free