services:
  - type: web
    name: varsity-plug
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn varsity_plug.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health/
    shell: |
      python manage.py shell

databases:
  - name: varsityplug-db
    databaseName: varsityplug
    user: varsityplug

services:
  - type: redis
    name: varsity-plug-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []