services:
  - type: web
    name: varsityplug
    env: python
    buildCommand: |
      echo "Installing dependencies..."
      pip install -r requirements.txt
      echo "Running migrations..."
      python manage.py showmigrations
      python manage.py migrate --noinput
      echo "Collecting static files..."
      python manage.py collectstatic --noinput
    startCommand: |
      echo "Starting application..."
      gunicorn varsity_plug.wsgi:application --bind 0.0.0.0:$PORT --chdir $(pwd)
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: varsityplug-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: varsityplug-nvg2.onrender.com
      - key: DEBUG
        value: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    shell: |
      python manage.py shell

databases:
  - name: varsityplug-db
    databaseName: varsityplug
    user: varsityplug

services:
  - type: redis
    name: varsity-plug-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []