# Generated by Django 5.2 on 2025-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_remove_documentupload_doc_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('minimum_aps', models.IntegerField(help_text='Minimum APS for Bachelor’s Degree entry')),
            ],
        ),
    ]
