# Generated by Django 5.1.6 on 2025-05-15 20:43

import django.db.models.deletion
from django.db import migrations, models

def copy_legacy_university_id_to_fk(apps, schema_editor):
    ApplicationStatus = apps.get_model('helper', 'ApplicationStatus')
    University = apps.get_model('helper', 'University')
    for app_status in ApplicationStatus.objects.all():
        if app_status.legacy_university_id:
            try:
                uni = University.objects.get(id=app_status.legacy_university_id)
                app_status.university = uni
                app_status.save()
            except University.DoesNotExist:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_add_selected_universities'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationstatus',
            unique_together={('student', 'university')},
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='legacy_university_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helper.university'),
        ),
        migrations.RunPython(copy_legacy_university_id_to_fk),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='legacy_university_id',
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.university'),
        ),
    ]
