# Generated by Django 5.1.6 on 2025-05-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_alter_applicationstatus_unique_together_and_more'),
    ]

    operations = [
    ]
