# Generated by Django 5.2 on 2025-04-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='aps_score',
            field=models.IntegerField(blank=True, help_text='Calculated APS from matric results', null=True),
        ),
    ]
