# Generated by Django 5.2 on 2025-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0004_studentprofile_aps_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='selected_universities',
            field=models.ManyToManyField(blank=True, related_name='interested_students', to='helper.university'),
        ),
    ]
