# Generated by Django 5.2 on 2025-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0005_studentprofile_selected_universities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('matric_certificate', 'Matric Certificate'), ('id_picture', 'ID Picture')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='aps_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='selected_universities',
            field=models.ManyToManyField(blank=True, to='helper.university'),
        ),
        migrations.AlterField(
            model_name='university',
            name='minimum_aps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
