# Generated by Django 5.1.6 on 2025-04-12 19:40

import helper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0006_remove_studentprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='aps_score',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='id_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='application_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[helper.models.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subscription_package',
            field=models.CharField(choices=[('basic', 'Basic Package'), ('standard', 'Standard Package'), ('premium', 'Premium Package'), ('ultimate', 'Ultimate Package')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subscription_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='province',
            field=models.CharField(default='id', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('id_picture', 'ID Picture'), ('grade_11_results', 'Grade 11 Results'), ('grade_12_results', 'Grade 12 Results'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
