# Generated by Django 5.1.6 on 2025-04-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0007_remove_studentprofile_aps_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='marks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
