# Generated by Django 5.1.6 on 2025-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0008_alter_studentprofile_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='stored_aps_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
