# Generated by Django 5.1.6 on 2025-04-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0009_studentprofile_stored_aps_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name_plural': 'Universities'},
        ),
    ]
