# Generated by Django 5.1.6 on 2025-05-01 12:12

import helper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0010_alter_documentupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='minimum_aps',
            field=models.IntegerField(validators=[helper.models.validate_minimum_aps]),
        ),
    ]
