# Generated by Django 5.1.6 on 2025-05-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0014_add_subscription_fields'),
        ('helper', '0014_add_verified_field'),
    ]

    operations = [
    ]
