# Generated by Django 5.1.6 on 2025-05-10 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0015_merge_20250510_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='subscription_date',
        ),
        migrations.AddField(
            model_name='university',
            name='application_fee',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('id_picture', 'ID Picture'), ('grade_11_results', 'Grade 11 Results'), ('grade_12_results', 'Grade 12 Results'), ('payment_proof', 'Proof of Payment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.university'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stored_aps_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='subscription_package',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('ultimate', 'Ultimate')], default='basic', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_verified', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.studentprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper.university')),
            ],
            options={
                'verbose_name': 'Application Status',
                'verbose_name_plural': 'Application Statuses',
                'ordering': ['-application_date'],
                'unique_together': {('student', 'university')},
            },
        ),
    ]
