# Generated by Django 5.1.6 on 2025-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0016_remove_studentprofile_subscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('id', 'ID Document'), ('matric_cert', 'Matric Certificate'), ('grade_11', 'Grade 11 Results'), ('payment_proof', 'Proof of Payment'), ('other', 'Other')], max_length=20),
        ),
    ]
