# Generated by Django 5.1.6 on 2025-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0017_alter_documentupload_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='not_started', max_length=20),
        ),
    ]
