# Generated by Django 5.1.6 on 2025-05-12 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0018_documentupload_verification_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='document_type',
            field=models.CharField(choices=[('id_picture', 'ID Picture'), ('grade_11_results', 'Grade 11 Results'), ('grade_12_results', 'Grade 12 Results'), ('payment_proof', 'Proof of Payment'), ('subscription_payment', 'Subscription Payment'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('not_paid', 'Not Paid'), ('pending', 'Pending Verification'), ('paid', 'Paid')], default='not_paid', max_length=20)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
