# Generated by Django 5.1.6 on 2025-05-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0019_alter_documentupload_document_type_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='subscription_status',
        ),
    ]
