# Generated by Django 5.1.6 on 2025-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0021_remove_subscription_status_field_again'),
    ]

    operations = [
        # This is a no-op migration to fix the migration state
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[]
        )
    ] 