# Generated by Django 5.1.6 on 2025-05-13 10:37

from django.db import migrations


def remove_subscription_status_field(apps, schema_editor):
    StudentProfile = apps.get_model('helper', 'StudentProfile')
    # Get all profiles
    for profile in StudentProfile.objects.all():
        # Check if the field exists
        if hasattr(profile, 'subscription_status'):
            # Remove the field
            delattr(profile, 'subscription_status')
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0021_remove_subscription_status_field_again'),
    ]

    operations = [
        migrations.RunPython(remove_subscription_status_field),
    ] 