# Generated by Django 5.1.6 on 2025-05-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0024_fix_migration_conflict'),
        ('helper', '0025_reset_migration_state'),
    ]

    operations = [
    ]
