# Generated by Django 5.1.6 on 2025-05-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0026_merge_20250514_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='subscription_status',
        ),
    ]
