# Generated by Django 5.1.6 on 2025-05-14 15:08

from django.db import migrations

def clear_applicationstatus(apps, schema_editor):
    ApplicationStatus = apps.get_model('helper', 'ApplicationStatus')
    ApplicationStatus.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0028_populate_universities'),
    ]

    operations = [
        migrations.RunPython(clear_applicationstatus),
    ]
