# Generated by Django 5.1.6 on 2025-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0029_clear_applicationstatus_for_static'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationstatus',
            unique_together={('student', 'university_id')},
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='university_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='selected_universities',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='university',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='selected_universities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
