# Generated by Django 5.1.6 on 2025-05-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0030_alter_applicationstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='university_id',
            field=models.IntegerField(),
        ),
    ]
