# Generated by Django 5.1.6 on 2025-05-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0031_alter_applicationstatus_university_id'),
        ('helper', '0031_fix_selected_universities'),
    ]

    operations = [
    ]
